### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by abbi1229** [ankitpokhrel/jira-cli#221]
1. Version:
    ```
    JiraCLI (Version="dev", GitCommit="", GoVersion="go1.17.3", BuildDate="", Compiler="gc", Platform="linux/amd64")
    Atlassian Jira (v8.13.11), on-premise.
    CentOS Linux release 7.8.2003 (Core) , Konsole 2.10.5
    ```
2. Steps
    ```
     ~/go/bin> jira issue view ISSUE-1
    ```
3. Debug
    ```
    fatal error: runtime: out of memory
    
    runtime stack:
    runtime.throw({0xcc40a2, 0x118c00000})
            /home/local/go/src/runtime/panic.go:1198 +0x71
    runtime.sysMap(0xc260c00000, 0x429680, 0x7fff957e1d28)
            /home/local/go/src/runtime/mem_linux.go:169 +0x96
    runtime.(*mheap).grow(0x13a8a20, 0x8c479)
            /home/local/go/src/runtime/mheap.go:1393 +0x225
    runtime.(*mheap).allocSpan(0x13a8a20, 0x8c479, 0x0, 0x1)
            /home/local/go/src/runtime/mheap.go:1179 +0x165
    runtime.(*mheap).alloc.func1()
            /home/local/go/src/runtime/mheap.go:913 +0x69
    runtime.systemstack()
            /home/local/go/src/runtime/asm_amd64.s:383 +0x49
    
    goroutine 1 [running]:
    runtime.systemstack_switch()
            /home/local/go/src/runtime/asm_amd64.s:350 fp=0xc00008d700 sp=0xc00008d6f8 pc=0x461480
    runtime.(*mheap).alloc(0x1188f2000, 0x8c479, 0x4, 0x0)
            /home/local/go/src/runtime/mheap.go:907 +0x73 fp=0xc00008d750 sp=0xc00008d700 pc=0x4259b3
    runtime.(*mcache).allocLarge(0x78137f, 0x1188f2000, 0xaf, 0x1)
            /home/local/go/src/runtime/mcache.go:227 +0x89 fp=0xc00008d7b0 sp=0xc00008d750 pc=0x416629
    runtime.mallocgc(0x1188f2000, 0x0, 0x0)
            /home/local/go/src/runtime/malloc.go:1082 +0x5c5 fp=0xc00008d830 sp=0xc00008d7b0 pc=0x40cba5
    runtime.growslice(0xc0001e30b5, {0xc0c8b80000, 0xc000175000, 0x16}, 0x20)
            /home/local/go/src/runtime/slice.go:261 +0x4ac fp=0xc00008d898 sp=0xc00008d830 pc=0x44a2cc
    strings.(*Builder).WriteString(...)
            /home/local/go/src/strings/builder.go:124
    github.com/ankitpokhrel/jira-cli/pkg/md/jirawiki.secondPass({0xc000175000, 0xc000132200, 0x20})
            /home/local/jira-cli-main/pkg/md/jirawiki/parser.go:130 +0x125 fp=0xc00008d9a0 sp=0xc00008d898 pc=0x7806c5
    github.com/ankitpokhrel/jira-cli/pkg/md/jirawiki.Parse({0xc0001e2a80, 0x904})
            /home/local/jira-cli-main/pkg/md/jirawiki/parser.go:83 +0x10b fp=0xc00008da10 sp=0xc00008d9a0 pc=0x7804eb
    github.com/ankitpokhrel/jira-cli/pkg/md.FromJiraMD(...)
            /home/local/jira-cli-main/pkg/md/md.go:23
    github.com/ankitpokhrel/jira-cli/internal/view.Issue.description({{0xc0000232a0, 0x1e}, 0xc00015a280, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}})
            /home/local/jira-cli-main/internal/view/issue.go:214 +0xa5 fp=0xc00008da68 sp=0xc00008da10 pc=0xb27405
    github.com/ankitpokhrel/jira-cli/internal/view.Issue.fragments({{0xc0000232a0, 0x1e}, 0xc00015a280, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}})
            /home/local/jira-cli-main/internal/view/issue.go:105 +0x165 fp=0xc00008dbd8 sp=0xc00008da68 pc=0xb25aa5
    github.com/ankitpokhrel/jira-cli/internal/view.Issue.RenderedOut({{0xc0000232a0, 0x1e}, 0xc00015a280, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}}, 0xc000165000)
            /home/local/jira-cli-main/internal/view/issue.go:63 +0xce fp=0xc00008dcc0 sp=0xc00008dbd8 pc=0xb24aae
    github.com/ankitpokhrel/jira-cli/internal/view.Issue.Render({{0xc0000232a0, 0x1e}, 0xc00015a280, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}})
            /home/local/jira-cli-main/internal/view/issue.go:52 +0xa5 fp=0xc00008dd18 sp=0xc00008dcc0 pc=0xb248e5
    github.com/ankitpokhrel/jira-cli/internal/cmd/issue/view.view(0xc0000bd400, {0xc000036620, 0x1, 0x2})
            /home/local/jira-cli-main/internal/cmd/issue/view/view.go:60 +0x172 fp=0xc00008ddb0 sp=0xc00008dd18 pc=0xb615f2
    github.com/spf13/cobra.(*Command).execute(0xc0000bd400, {0xc000036600, 0x2, 0x2})
            /home/local/jira-cli-main/vendor/github.com/spf13/cobra/command.go:860 +0x5f8 fp=0xc00008de70 sp=0xc00008ddb0 pc=0x586278
    github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bc280)
            /home/local/jira-cli-main/vendor/github.com/spf13/cobra/command.go:974 +0x3bc fp=0xc00008df28 sp=0xc00008de70 pc=0x58697c
    main.main()
            /home/local/jira-cli-main/cmd/jira/main.go:12 +0x1e fp=0xc00008df80 sp=0xc00008df28 pc=0xb6b01e
    runtime.main()
            /home/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00008dfe0 sp=0xc00008df80 pc=0x435a67
    runtime.goexit()
            /home/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00008dfe8 sp=0xc00008dfe0 pc=0x463561
    ```

Some of tickets can't open by using "view".
I'm not sure what issue will triggered this.
The content looks normal.

**Comment by ankitpokhrel** [comment]
Hi @abbi1229 from the stack trace I see that this could be an issue with [wiki parser](https://github.com/ankitpokhrel/jira-cli/blob/main/pkg/md/jirawiki/parser.go). However, I am not able to reproduce this in the setup I currently have.

It would be great if you can provide more details on what kind of contents you are using in the description eg: lists, table, links etc. A sample description might help to reproduce the issue.

**Comment by abbi1229** [comment]
Hi @ankitpokhrel,
I made some experiments.
The key is about **{noformat}**.
This is the easiest way to reproduce the issue.
  ```
  {noformat}
  1
  2
  3
  4
  5
  6
  {noformat}
  {noformat}
  7
  {noformat}
  ```
**Can't reproduce**:
The following conditions works fine.
  ```
  {noformat}
  line1
  line2
  line3
  line4
  line5
  line6
  {noformat}
  
  {noformat}
  line7
  {noformat}
  ```
  ```
  {noformat}
  line1
  line2
  line3
  line4
  line5
  line6
  {noformat}
  {noformat}
  {noformat}
  ```
  ```
  {noformat}
  line1
  line2
  line3
  line4
  line5
  {noformat}
  {noformat}
  line6
  {noformat}
  ```

Our jira version is v8.13.11, on-premise.
I had tried to reproduce this on cloud JIRA.
But, This issue can't reproduce by using cloud JIRA.

**Comment by ankitpokhrel** [comment]
@abbi1229 Thank you for the details. I would not have been able to reproduce this otherwise.

Please try with new build and let me know how it goes. Since the release is not yet available, you can either [compile from source](https://github.com/ankitpokhrel/jira-cli#development) or if you are using homebrew you can build binary from `HEAD` (requires `make`, `git` and `go`)

```sh
brew uninstall jira-cli
brew install jira-cli --HEAD
```

**Comment by abbi1229** [comment]
Hi @ankitpokhrel ,
Now it works perfectly.
Thanks.
