### ISSUE TITLE
jira issue view: fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by realtime-neil** [ankitpokhrel/jira-cli#349]
**Describe the bug**

Calling `jira issue view` with a large `--comments` number causes `fatal error: runtime: out of memory`:

**Please provide following details**
1. JiraCLI Version:
    ```
    $ jira version
    (Version="v0.3.1-0.20220420190240-75cfa199c5fe", GitCommit="", CommitDate="", GoVersion="go1.18.1", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    cloud
    ```
3. What operating system are you using? Also mention version.
    ```
    Ubuntu 20.04
    ```
4. What terminal are you using? Also mention version.
    ```
    $ gnome-terminal --version
    # GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
    ```

**To Reproduce**

```
$ jira issue view --plain --comments 2147483647 FOOBAR-12345
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xdd0328?, 0x1000000000?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sysMap(0xc000c00000, 0x7f1469755d38?, 0x7f1469755da0?)
	/usr/local/go/src/runtime/mem_linux.go:189 +0x11b
runtime.(*mheap).grow(0x150d060, 0x800000?)
	/usr/local/go/src/runtime/mheap.go:1404 +0x225
runtime.(*mheap).allocSpan(0x150d060, 0x800000, 0x0, 0x0)
	/usr/local/go/src/runtime/mheap.go:1170 +0x171
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc00099f7b8 sp=0xc00099f7b0 pc=0x4631a0
runtime.(*mheap).alloc(0x1000000000?, 0x800000?, 0xbf?)
	/usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc00099f800 sp=0xc00099f7b8 pc=0x428105
runtime.(*mcache).allocLarge(0xc00099f890?, 0xfffffffe0, 0x0)
	/usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc00099f850 sp=0xc00099f800 pc=0x418605
runtime.mallocgc(0xfffffffe0, 0xcfee00, 0x1)
	/usr/local/go/src/runtime/malloc.go:1096 +0x5a5 fp=0xc00099f8c8 sp=0xc00099f850 pc=0x40ebc5
runtime.makeslice(0x1000000000008?, 0xcaebc0?, 0x0?)
	/usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc00099f8f0 sp=0xc00099f8c8 pc=0x44c232
github.com/ankitpokhrel/jira-cli/internal/view.Issue.comments({{0xc00002c930, 0x26}, 0xc000538000, {0x1, 0x0, 0x0, {0x0, 0x0, 0x0}}, {0x7fffffff}})
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/internal/view/issue.go:314 +0x3f fp=0xc00099fa90 sp=0xc00099f8f0 pc=0xc204bf
github.com/ankitpokhrel/jira-cli/internal/view.Issue.String({{0xc00002c930, 0x26}, 0xc000538000, {0x1, 0x0, 0x0, {0x0, 0x0, 0x0}}, {0x7fffffff}})
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/internal/view/issue.go:105 +0x7ae fp=0xc00099fbf0 sp=0xc00099fa90 pc=0xc1dcce
github.com/ankitpokhrel/jira-cli/internal/view.Issue.renderPlain({{0xc00002c930, 0x26}, 0xc000538000, {0x1, 0x0, 0x0, {0x0, 0x0, 0x0}}, {0x7fffffff}}, ...)
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/internal/view/issue.go:379 +0xd3 fp=0xc00099fc88 sp=0xc00099fbf0 pc=0xc20ef3
github.com/ankitpokhrel/jira-cli/internal/view.Issue.Render({{0xc00002c930, 0x26}, 0xc000538000, {0x1, 0x0, 0x0, {0x0, 0x0, 0x0}}, {0x7fffffff}})
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/internal/view/issue.go:57 +0xd4 fp=0xc00099fce8 sp=0xc00099fc88 pc=0xc1d194
github.com/ankitpokhrel/jira-cli/internal/cmd/issue/view.view(0xc00081b180?, {0xc0003fbdc0, 0x1, 0x4?})
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/internal/cmd/issue/view/view.go:69 +0x1b7 fp=0xc00099fd98 sp=0xc00099fce8 pc=0xc59717
github.com/spf13/cobra.(*Command).execute(0xc00081b180, {0xc0003fbd80, 0x4, 0x4})
	/home/neil/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x663 fp=0xc00099fe70 sp=0xc00099fd98 pc=0x597403
github.com/spf13/cobra.(*Command).ExecuteC(0xc000451b80)
	/home/neil/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3b4 fp=0xc00099ff28 sp=0xc00099fe70 pc=0x597a94
main.main()
	/home/neil/go/pkg/mod/github.com/ankitpokhrel/jira-cli@v0.3.1-0.20220420190240-75cfa199c5fe/cmd/jira/main.go:12 +0x1e fp=0xc00099ff80 sp=0xc00099ff28 pc=0xc650de
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x212 fp=0xc00099ffe0 sp=0xc00099ff80 pc=0x437d92
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc00099ffe8 sp=0xc00099ffe0 pc=0x4653c1
```

**Expected behavior**

Unknown.

**Screenshots**

Not applicable.

**Additional context**

Not applicable.

**Comment by ankitpokhrel** [comment]
Hi @realtime-neil, Thank you for reporting the issue. Could you please check if #350 fixes this for you?

```sh
go install github.com/ankitpokhrel/jira-cli/cmd/jira@fix-issue-349
```

**Comment by realtime-neil** [comment]
> Hi @realtime-neil, Thank you for reporting the issue. Could you please check if #350 fixes this for you?
> 
> ```shell
> go install github.com/ankitpokhrel/jira-cli/cmd/jira@fix-issue-349
> ```

That works!

```
$ go install github.com/ankitpokhrel/jira-cli/cmd/jira@fix-issue-349 && jira version && jira issue view --plain --comments $((2**31-1)) FOOBAR-12345 >/dev/null ; echo $?
(Version="v0.3.1-0.20220423070413-696ec3dd3470", GitCommit="", CommitDate="", GoVersion="go1.18.1", Compiler="gc", Platform="linux/amd64")
0
```
