### ISSUE TITLE
Segfault on `v` action for any issue in Sprints layout

### ISSUE THREAD

**Issue by XVilka** [ankitpokhrel/jira-cli#595]
**Describe the bug**
A crash on the `v` action in Sprints layout for any issue:
```
┘panic: runtime error: invalid memory address or nil pointer dereference                                                            ║                                                                                                                                                       ║
 [signal SIGSEGV: segmentation violation code=0x2 addr=0xa0 pc=0x102d7acd4]                                                                                                                                          ║
                                                             ║                                                                                                                                                       ║
                                                             ║             goroutine 29 [running]:                                                                                                                   ║
                                                             ║                                    github.com/ankitpokhrel/jira-cli/internal/view.Issue.header({{0x14000b4e828, 0x17}, 0x0, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})                                       ║                                                                                                                                                       ║
                      	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/internal/view/issue.go:203 +0x64                                                                                                 ║
                                                             ║                                                      github.com/ankitpokhrel/jira-cli/internal/view.Issue.fragments({{0x14000b4e828, 0x17}, 0x0, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})                  ║                                                                                                                                                       ║
                                           	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/internal/view/issue.go:127 +0x98                                                                         ║
                                                             ║                                                                              github.com/ankitpokhrel/jira-cli/internal/view.Issue.RenderedOut({{0x14000b4e828, 0x17}, 0x0, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...}, ...)                                                                                                                                           ║
                                                             ║            	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/internal/view/issue.go:76 +0xac                                          ║
                                                             ║                                                                                                             github.com/ankitpokhrel/jira-cli/internal/view.(*SprintList).Render.func1.2({0x10306db80?, 0x0?})       ║                                                                                                                                                       ║
                                                      	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/internal/view/sprint.go:66 +0xb4                                                                 ║
                                                             ║                                                                                      github.com/ankitpokhrel/jira-cli/pkg/tui.(*Preview).initContents.func1.2.1(0x140001b6690, 0x2, 0x28?, 0x14000a60f50?)          ║                                                                                                                                                       ║
                                                   	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/pkg/tui/preview.go:255 +0xe4                                                                     ║
                                                             ║                                                                                  github.com/ankitpokhrel/jira-cli/pkg/tui.(*Preview).initContents.func1.2()                                                         ║                                                                                                                                                       ║
    	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/pkg/tui/preview.go:259 +0x30═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
 Showing 20 results from board "XXX Kanban" of project "YYY"                       created by github.com/ankitpokhrel/jira-cli/pkg/tui.(*Preview).initContents.func1
                                                                                                                                                                                 	/Users/ankitpokhrel/go/src/github.com/ankitpokhrel/jira-cli/pkg/tui/preview.go:244 +0x264
```

**Please provide following details**

1. JiraCLI Version:
```
  (Version="1.3.0", GitCommit="ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed", CommitDate="2023-01-02T09:59:32+00:00", GoVersion="go1.19.4", Compiler="gc", Platform="darwin/arm64")
```
2. Are you using Jira cloud or on-premise jira server?
```
SERVER INFO
-----------

Version: 	 8.20.6
Build Number: 	 820006
Deployment Type: Server
Default Locale:  
```

3. What operating system are you using? Also mention version.
    ```
    macOS 13.2 ARM64
    ```
4. What terminal are you using? Also mention version.
    ```
     iTerm 2 Build 3.4.19
    ```

**To Reproduce**

1. `jira sprint list`
2. Select any sprint and issue, then press `v`
3. See error

**Expected behavior**
No crash

**Comment by ankitpokhrel** [comment]
That's strange! It looks like the API is not returning [Assignee field](https://github.com/ankitpokhrel/jira-cli/blob/ed84fe74f68ba1b2cf0504a931ca09a03b2c9fed/internal/view/issue.go#LL203C35-L203C35). I cannot reproduce this behavior in `8.22.2`, are you able to add assignee from the UI?

Also, could you please check what response you get with this cURL request and what you get in the Assignee field?

```sh
$ curl --request GET \
  --url 'https://<host>/rest/api/2/issue/<issue-key>' \
  --user "<user>:$JIRA_API_TOKEN" \
  --header 'Accept: application/json'
```

**Comment by XVilka** [comment]
@ankitpokhrel indeed, in the JSON returned from this curl request there is no 'Assignee' field at all, not even null-valued one.

**Comment by ankitpokhrel** [comment]
@XVilka This looks something specific to your installation, are you able to set assignee from the UI? Also wondering if the problem is only with that particular field or other fields are missing as well? (Apologies for late response)

**Comment by XVilka** [comment]
@ankitpokhrel yes, recently upgraded Jira version to 9.4.4 and also pulled latest code from git, the issue is still here. I am able to set assignee from the UI.
